DEBUG = True
API_LOCATION = '/api'
APP_SCHEME = 'http'
SQLALCHEMY_DATABASE_URI = 'postgresql://mreport_user1:mreport@localhost:5432/dataviz1'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SCHEMA = "data" ## Comment this line if you don't need schema or if you use SQLite
MREPORT_REPORTS = "backend/reports"
MREPORT_LOCATION = "/mreport"
ADMIN_LOCATION = "/admin"
