FROM python:3.7-slim

RUN useradd -r -m apprunner

USER apprunner

ENV HOME=/home/apprunner
ENV PATH=$HOME/.local/bin:$PATH

WORKDIR /home/apprunner

COPY requirements.txt .
COPY config.py .
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --user -r requirements.txt

COPY --chown=apprunner:apprunner backend backend
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --user backend && pip install --user gunicorn

CMD ["gunicorn", "-w 4", "-b 0.0.0.0:8000", "backend:app"]
