#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $MREPORT_DATABASE_USER WITH PASSWORD '$MREPORT_DATABASE_PWD';
  CREATE DATABASE $MREPORT_DATABASE_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $MREPORT_DATABASE_NAME TO $MREPORT_DATABASE_USER;
EOSQL

sed -e 's/$MREPORT_DATABASE_USER/'"$MREPORT_DATABASE_USER"'/g' -e 's/$MREPORT_DATABASE_SCHEMA/'"$MREPORT_DATABASE_SCHEMA"'/g' /tmp/script.sql | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d $MREPORT_DATABASE_NAME
